http:
  routers:
    grafana_https:
      service: "grafana-traefik@docker"
      rule: "Host(`grafana.domain.com`)"
      entryPoints:
        - "web"
        - "websecure"
      tls:
        certResolver: "https-resolver"
