http:
  routers:
    dashboard_https:
      service: "api@internal"
      rule: "Host(`traefik.domain.com`)"
      entryPoints:
        - "web"
        - "websecure"
      tls:
        certResolver: "https-resolver"
      middlewares:
        - "traefikauth"
    prometheus:
      service: "prometheus@internal"
      entryPoints:
        - "metrics"
      rule: "PathPrefix(`/metrics`)"
